### ISSUE TITLE
Clarify Sire intro

### ISSUE THREAD

**Issue by kjekac** [deathtothecorporation/plunder-docs#5]
Article here: https://opfn.gitbook.io/pallas/sire/intro

- [x] Maybe we should include the "there's no input prompt" part in one of the code blocks? If someone is reading without following along in the repl that will make the code blocks we include less confusing.
- [x] You first use `=` infix and then prefix without explaining that they are the same.
- [x] I suggest that we only use `|` and `(..)` for function application for as long as possible, and immediately explain that `(add 1 3)` is short form for `(| add 1 3)`, that all runes can be written several different ways ("you've just seen two of them, and you saw another with `=` above"), and that `|` is the only rune which can omitted in this way. Or maybe that we only use `|` and `(..)` but don't explain the other part? Not sure. But exclude `-` at this stage for sure.
- [x] Regarding strings and nats, i would simply not explain how strings are rendered (`%` vs `{..}`) at the point that you do. Instead just talk about nats, and at the first example where a nat renders as a string, just explain that it was rendered as a string (and maybe add that we'll talk about why and how strings are displayed later).
- [x] Nats are not called "nouns". They might be called "atoms" occasionally, but i think we should stop that? "Nouns" is a somewhat imprecise term in Pallas. Most often we use it to refer to any PLAN value (so pins laws apps and nats). Quite possible that the main usage there is to distinguish between a (data) jet and its formal "noun" representation? I'm also pretty sure both i and Sol have used it to mean "nested rows" at some occasion, since nested rows of nats are very similar to Urbit cells of atoms, i.e. nouns. It's an imperfect analogy to use since you could stuff your rows with laws instead of nats, but otoh it's also probably how you would implement nouns if you wanted to interop with Urbit.
- [x] I'd say you "create a bar" rather than "declare a bar". Declaring connotes state-manipulation to me, which values don't do. (The only things in Sire i can think of that "declare" anything are `####`, `=` and `??`.) There is at least one more example of this usage in the section on lists.
- [x] I know what you're getting at but i think it's bad to encourage users to think of bars and strings interchangeably, at the very least without *in the same sentence* mentioning that there are conversion functions between them and that these need to be used.
- [x] Bars don't have extra baggage that contains information about the byte-width. They have extra baggage which allows the runtime to see that a particular nat should be optimized into a byte-array in memory. The width is assumed to always be a multiple of 8, i actually don't know what happens if it isn't. If you construct bars using the library functions (including the `#b` syntax) then you'll always be fine. (It's worth noting that the interface between PLAN and the runtime basically never includes such safeguards or checks. PLAN is pretty safe in its own right (purity gives you a lot) but there are lots of places for you to get a `0` when you expected a function and shit like that.)
- [x] In the list section, maybe it's worth mentioning that we need parens around the list because of the infix `=`, or simply use `=` prefix?
- [x] Already mentioned this in the other comments but `=?=` is used without introduction.

**Comment by vcavallo** [comment]
Closed by https://github.com/deathtothecorporation/plunder-docs/pull/14
