### ISSUE TITLE
Clarify advanced Sire section

### ISSUE THREAD

**Issue by kjekac** [deathtothecorporation/plunder-docs#8]
Article: https://opfn.gitbook.io/pallas/sire/advanced

- [x] Explanation of the col macro is wordy and imprecise. In *my* opinion:
  1. Start with just showing the rewrite from `:` to `&`, since you just explained `&`.
  2. For each one of `gen` and `maybeCase`, write two examples: one which uses `&` and one which uses `:`. Highlight how the last argument to the function is "omitted" in the examples that use `:`.
  3. _Maybe_ explain that this is very useful for callbacks/continuations and show a cog example which uses it for that.
- [x] Pins aren't similar to let bindings (though i'm curious in which way they seem like they are, so that we can avoid others making that same mistake). If anything they're similar to top-level bindings, but even that's stretching it more than i would like. (To be precise: top-level bindings in Sire *create* pins, but not all languages need to do this for all their top-level definitions, and pins are useful for other things too.)

  Pins are two things. Inside the system they're semantically meaningless magical boxes that you sometimes have to unpack to get the stuff you want. This annoyance can be enforced using a type system, if it ever needs to reach the end user at all -- not sure. In the runtime, they're essentially memory pages (except that they aren't of fixed size, so we need to do some packing when we map these onto actual memory pages). Together, all the pins in a machine form a Merkle-DAG of such "variable-width memory pages", the bottom of whose nodes will basically always be all the top-level defs from Sire's bootstrapping sequence, followed by convenience things and cog/kern stuff, and then user-generated stuff at the top. (All of this should probably not be explained in this part of the docs, i'm clarifying for your sake.)

**Comment by vcavallo** [comment]
I might have made the col macro section worse @kjekac : https://github.com/deathtothecorporation/plunder-docs/pull/19

it's definitely not _shorter_, that's for sure... I think my own initial hurdle with the col macro got me so skittish about it that I'm assuming other people will need verbose hand-holding through it. this may not be the case!
